// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq-peiHatxVZ_0H0lC8-2LpUhbebcyDFA',
    appId: '1:399167421956:web:88f4601c2350f5408e3f51',
    messagingSenderId: '399167421956',
    projectId: 'login-providers-70a42',
    authDomain: 'login-providers-70a42.firebaseapp.com',
    storageBucket: 'login-providers-70a42.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzm-BxfrLbsF1NRMb0KXE0LpmK5U2TQko',
    appId: '1:399167421956:android:e8b3516ad4bdf7748e3f51',
    messagingSenderId: '399167421956',
    projectId: 'login-providers-70a42',
    storageBucket: 'login-providers-70a42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYXUM9IMkpIjozaVDEvAgcmMBdSnRYll0',
    appId: '1:399167421956:ios:bf570d0cd2d0fba78e3f51',
    messagingSenderId: '399167421956',
    projectId: 'login-providers-70a42',
    storageBucket: 'login-providers-70a42.appspot.com',
    iosClientId: '399167421956-5rdtav6p54vqssa8o6h8srsh5298a01t.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginProviders',
  );
}
